databases:
  - name: sumuma
    plan: free
    databaseName: sumuma
    user: sumuma

services:
  - type: web
    plan: free
    name: sumuma
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'poetry run python -m gunicorn sumuma.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sumuma
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: POETORY_VERSION
        value: 2.1.3
      - key: DEBUG
        value: 'False'